# Generated by Django 2.0.3 on 2019-04-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190423_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsy',
            name='anatomical_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biopsies', to='api.AnatomicalPart', verbose_name='Anatomical Part'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='enzyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_types', to='api.Enzyme', verbose_name='Enzyme'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_types', to='api.CellCategory', verbose_name='Cell Category'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='cell_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.CellDistribution', verbose_name='Cell Distribution'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.Coating', verbose_name='Coating'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.ContainerType', verbose_name='Container Type'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='enzyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.Enzyme', verbose_name='Enzyme'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='morphology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.Morphology', verbose_name='Morphology'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.Passage'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='pigmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.Pigmentation', verbose_name='Pigmentation'),
        ),
        migrations.AlterField(
            model_name='skinlayer',
            name='enzyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_layers', to='api.Enzyme', verbose_name='Enzyme'),
        ),
        migrations.AlterField(
            model_name='skinlayer',
            name='layer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_layers', to='api.LayerType', verbose_name='Skin Layer Type'),
        ),
        migrations.AlterField(
            model_name='subbiopsy',
            name='cut_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_biopsies', to='api.CutMethod', verbose_name='Cut Method'),
        ),
    ]
