version: '3'
services:
  frontend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2019-02/personal-projects/eskin/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"  # For nginx
    volumes:
      - ./frontend:/usr/src/app
      - '/usr/src/app/node_modules'
    command: "npm run start"

  project:
    image: "${CI_PIPELINE_ID}:${CI_BUILD_REF_NAME}"
    volumes:
      - ./htmlcov:/project/htmlcov
